server:
  tomcat:
    max-http-form-post-size: 200MB
spring:
  profiles:
    include: secret

  datasource:
    url: jdbc:mysql://localhost:3306/memoraize?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: memoraize
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 50MB      # 파일 1개 최대 크기
      max-request-size: 200MB  # 요청 전체 최대 크기 (여러 장 업로드 고려)

logging:
  level:
    hangeureut: DEBUG
    org.springframework: INFO
